spring:
  application:
    name: elastic-springjpa-crud
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    show-sql: true
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
